{
    "id": "65e58e5435880dab766f4fba",
    "lastName": "Ngọc",
    "firstName": " Hân",
    "name": "Ngọc Hân",
    "phone": "0356110555",
    "birthday": null,
    "email": "ngochan5899@gmail.com",
    "physicalId": "381324***",
    "address": "Quận 3, HCM",
    "customerDMSType": null,
    "dmsCode": null,
    "group": null,
    "listTagCampaigns": [
        "XpanderCrossMY20"
    ],
    "listTagModels": [
        "Attrage",
        "Xpander",
        "Xpander Cross"
    ],
    "expectBuyDate": null,
    "lastActivityTime": null,
    "firstActivityTime": null,
    "isHaveSurvey": false,
    "createdAt": "2023-07-06T08:15:45Z",
    "leadCreatedAt": null,
    "duplicateType": null,
    "isDuplicate": false,
    "dealerCode": "0414",
    "broker": "hien.tester",
    "customerSource": "d1115055937ca4545cc5b796174faa7e",
    "customerChannel": "358acb9bcaa57c63cb2106e2984b6268",
    "leadChannel": null,
    "leadSource": null,
    "contactPerson": null,
    "city": "0",
    "customerSourceName": null,
    "customerChannelName": null,
    "leadChannelName": null,
    "leadSourceName": null,
    "dateOfIssue": null,
    "placeOfIssue": "Cà Mau",
    "sourceOnline": null,
    "mediumOnline": null,
    "campaignOnline": null,
    "refererUrl": null,
    "keywordOnline": null,
    "url": null,
    "tid": null,
    "cid": null,
    "isHavePO": false,
    "dateOfPO": null,
    "stage": "a18a0eb147b3a603c90797eca2312a78",
    "firstBuyLevel": null,
    "callCenterStatus": null,
    "oldId": "1828319"
}